### Auth Test - Caribe Digital v2.0

@baseUrl = http://localhost:3000

# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "admin@caribedigital.cr",
    "password": "Password123!",
    "fullName": "Admin Caribe"
}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@caribedigital.cr",
    "password": "Password123!"
}
