import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Language = 'es' | 'en';

interface LanguageState {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    es: {
        // General
        'search_placeholder': '¿Qué se te antoja hoy?',
        'hero_title': 'SABORES DEL PARAÍSO',
        'near_me': 'Cerca de mí',
        'near_you': 'Cerca de ti',
        'coming_soon': '¡Ya casi llega!',
        'loading': 'Cargando buenas vibras...',
        'retry': 'Probar de nuevo',
        'connection_error': 'Uy, se nos fue la señal',
        'connection_error_desc': 'Parece que el mar está picado. Revisa tu conexión e intenta otra vez.',

        // Navigation
        'explore': 'Explorar',
        'map': 'Mapa',
        'events': 'Eventos',
        'about': 'La Tribu',
        'sustainability': 'Eco Vida',
        'blog': 'Historias',
        'profile': 'Mi Perfil',
        'history': 'Mis Pedidos',
        'my_orders': 'Mis Pedidos',
        'logout': 'Cerrar Sesión',
        'admin_panel': 'Panel de Control',
        'dashboard': 'Mi Negocio',
        'courier_central': 'Central de Entregas',

        // Auth
        'login': 'Ingresar',
        'register': 'Unirme',
        'welcome_jungle': 'Bienvenido a la Jungla',
        'enter_paradise': 'Entrar al Paraíso',
        'join_tribe': 'Únete a la Tribu',
        'email_label': 'Tu Correo',
        'password_label': 'Clave Secreta',
        'no_account': '¿Aún no eres parte?',
        'has_account': '¿Ya tienes cuenta?',
        'auth_error': 'Mmm, esos datos no nos suenan.',

        // Cart
        'your_order': 'Tu Canasta',
        'empty_cart': 'Tu canasta está vacía',
        'empty_cart_desc': '¡Llénala de sabor caribeño!',
        'subtotal': 'Subtotal',
        'delivery_fee': 'Envío',
        'courier_tip': 'Propina al Repartidor',
        'total': 'Total a Pagar',
        'place_order': 'Confirmar Pedido',
        'add_notes': '¿Algún detalle extra?',
        'notes_placeholder': 'Ej: Sin culantro, salsa aparte...',

        // Categories & Filters
        'all': 'Todo',
        'restaurants': 'Restaurantes',
        'cafes': 'Cafecitos',
        'seafood': 'Del Mar',
        'essentials': 'Lo Básico',
        'eco_friendly': '100% Eco',

        // Footer & Community
        'support_wa': 'Escríbenos al WhatsApp',
        'order_help': '¿Ayuda con tu pedido?',
        'rights_reserved': 'Todos los derechos reservados, mae.',
        'made_with_love': 'Hecho con ❤️ en el Caribe',
        'pura_vida': '¡Pura Vida!',

        // Sort
        'sort_az': 'A-Z',
        'sort_rating': 'Los Favoritos',
        'sort_distance': 'A la vuelta',
        'new': 'Nuevo',
        'local_establishment': 'Establecimiento Local',
        'inactive': 'Inactivo',
        'closed': 'Cerrado',
        'busy': 'Ocupado',
        'operational': 'Operativo',
        'active': 'ACTIVA',
        'live': 'En Vivo',
        'coco_points': 'Coco Puntos',

        // Profile & Dashboard
        'abort': 'ABORTAR',
        'edit': 'EDITAR',
        'next_objective': 'PRÓXIMO OBJETIVO',
        'reward_incoming': 'Recompensa en camino',
        'points_left': 'PUNTOS RESTANTES',
        'rewards_hub': 'CENTRO DE CANJES',
        'request_reinforcements': 'SOLICITAR REFUERZOS',
        'history_title': 'HISTORIAL',
        'history_desc': 'REGISTRO DE OPERACIONES',
        'billing_title': 'FACTURACIÓN',
        'billing_desc': 'FACTURACIÓN ELECTRÓNICA',
        'control_center': 'Centro de Control',
        'admin_panel_desc': 'Panel de Administración',
        'ops_panel_desc': 'Panel de Operaciones',
        'assistant_title': 'ASISTENTE',
        'assistant_desc': 'UPLINK DIRECTO CON COCO',
        'disconnect': 'DESCONECTAR',
        'vehicle': 'Vehículo',
        'swarm_config': 'Configuración de Enjambre',
        'type': 'Tipo',
        'plate': 'Placa',
        'status': 'Estatus',
        'ops_clearance': 'Clearance de Operación',
        'verification': 'Verificación',
        'security': 'Seguridad',
        'lvl_1_access': 'Acceso Nvl 1',
        'undefined': 'No Definido',
        'proximity': 'PROXIMIDAD',
        'sustainability_metric': 'SOSTENIBILIDAD',

        // Footer
        'footer_desc': 'La plataforma definitiva para el Caribe Sur. Comida, logística y comunidad.',
        'community': 'Comunidad',
        'legal': 'Legal',
        'privacy_policy': 'Privacidad (Ley 8968)',
        'terms_of_use': 'Términos de Uso',
        'refunds': 'Reembolsos',
        'coming_soon_terms': '¡Próximamente! Los términos están en revisión legal.',
        'coming_soon_refunds': '¡Próximamente! Estamos definiendo la política de reembolsos.',

        // Merchant Dashboard
        'net_revenue': 'Ingreso Neto',
        'order_queue': 'Cola de Pedidos',
        'invoices_emitted': 'Facturación',
        'rating_caribe': 'Rating Caribe',
        'tactical_performance': 'Rendimiento Táctico',
        'daily_revenue': 'Ingresos netos por día',
        'transparency': 'Transparencia',
        'gross_sales': 'Venta Bruta',
        'commission_fee': 'Comisión (5%)',
        'your_balance': 'Tu Balance',
        'view_payouts': 'Ver Detalles de Pago',
        'customer_feedback': 'Feedback de Clientes',
        'reviews_count': 'Reseñas',
        'no_reviews': 'Sin reseñas aún',
        'caribe_user': 'Usuario Caribe',
        'excellent_service': 'Excelente servicio',
        'order_management': 'Gestión de Pedidos',
        'active_orders': 'pedidos activos',
        'sync_satellite': 'Sincronizando con satélite...',
        'tactical_silence': 'Silencio Táctico',
        'no_active_orders': 'No hay pedidos activos en este momento. ¡Buen momento para revisar tu inventario!',
        'quick_stock': 'Stock Rápido',
        'search_product': 'Buscar producto...',
        'syncing': 'Sincronizando...',
        'no_results': 'Sin resultados',
        'stock_changes_hint': 'Los cambios se reflejan al instante en la app del cliente',
        'store_status_updated': 'Estado de tienda actualizado',
        'error_updating_status': 'Error al actualizar estado',
        'service_mode_updated': 'Modo de servicio actualizado',
        'status_updated': 'Estado actualizado',
        'sync_command_center': 'Sincronizando Command Center...',
        'client': 'Cliente',
        'command': 'Comando',
        'inventory': 'Inventario',
        'marketing': 'Marketing',
        'hacienda': 'Hacienda',
        'status_pending': 'PENDIENTE',
        'status_preparing': 'PREPARANDO',
        'status_ready': 'LISTO',
        'status_delivered': 'ENTREGADO',
        'status_cancelled': 'CANCELADO',
        'filter_all': 'TODOS',
        'product_default': 'Producto',
        'guest': 'Invitado',
        'pickup': 'Recoger',
        'move_to': 'Mover a',
        'my_business': 'Mi Negocio',
        'status_synced': 'Sincronizado',
        'status_offline': 'Desconectado',
        'status_on_way': 'En Camino',
        'busy_mode': 'Modo Saturado',
        'status_active': 'Activado',
        'status_normal': 'Normal',
        'store_status_label': 'Estado Tienda',
        'status_online': 'En Línea',
        'settings': 'Configuración',
        'new_order': '¡NUEVA ORDEN!',
        'customer': 'Cliente',
        'enter_command': 'ENTRAR AL COMANDO',
        'order_total': 'Total Pedido',
        // Audit 2: Utilities
        'bus_schedules': 'Horarios',
        'bus_company': 'MEPE & Caribe Sur',
        'bus_direct': 'Directo',
        'city_sjo': 'SJO',
        'city_pv': 'PV',
        'city_limon': 'Limón',
        'bus_duration': '~4.5h',
        'freq_hourly': 'Cada hora',
        'bus_warning': 'Llega 30 min antes. Compra boletos en ventanilla.',
        'push_title': '¿Activar Notificaciones?',
        'push_desc': 'Recibe alertas instantáneas sobre el estado de tus pedidos y ofertas exclusivas.',
        'push_later': 'Ahora No',
        'push_enable': 'Activar',
        'push_success_title': '🎉 Notificaciones Activadas',
        'push_success_desc': 'Recibirás alertas de tus pedidos y ofertas especiales',
        // Audit 3: Global Notifications
        'status_update_toast': 'Estado actualizado en tiempo real',
        'new_order_received': '¡Nuevo Pedido Recibido!',
        'new_mission': '🚀 Nueva misión disponible',
        'mission_desc': 'Comercio cercano necesita recolecta',
        'driver_arriving': '🚀 ¡El repartidor está llegando!',
        'inventory_updated': 'Inventario actualizado',
        'inventory_desc': 'La disponibilidad de productos ha cambiado.',
        'session_expired': 'Sesión Expirada',
        'session_expired_desc': 'Tu sesión de tiempo real ha caducado. Reingresando...',
        // Audit 4: Map Experience
        'search_map_placeholder': 'Buscar eventos o locales...',
        'dynamic_weather': 'Clima Dinámico',
        'tactical_scanlines': 'Scanlines Tácticas',
        'show_merchants': 'Mostrar Locales',
        'show_events': 'Mostrar Eventos',
        'strategic_patrol_mode': 'Modo Patrulla Estratégico',
        'ambient_cycle': 'Ciclo de Ambiente',
        'my_location': 'Mi Ubicación',
        'categories': 'Categorías',
        'visualization': 'Visualización',
        'scan_lines': 'Líneas Scan',
        'places': 'Locales',
        'gps': 'GPS',
        'patrol': 'Patrulla',
        'ambience': 'Ambiente',
        'active_mission': 'Misión Activa',
        'private_mission': 'Misión Privada',
        'release_camera': 'Soltar Cámara',
        'fix_camera': 'Fijar Cámara',
        'destination': 'Destino',
        'open_chat': 'Abrir Chat',
        'waze_nav': 'Navegar con Waze',
        'pickup_order': 'RECOGER PEDIDO',
        'complete_delivery': 'COMPLETAR ENTREGA',
        'featured_event': 'Evento Destacado',
        'attendees': 'Asistentes',
        'buy_ticket_btn': 'COMPRAR ENTRADA',
        'vip_event': 'Evento VIP',
        // Map Indicators
        'time_sunrise': 'Amanecer Caribeño',
        'time_day': 'Pleno Sol',
        'time_golden': 'Hora Dorada',
        'time_night': 'Noche Tropical',
        'time_stealth': 'Modo Stealth',
        'exploration_mode': 'Modo Exploración Activo',
        'sync_radar': 'Sincronizando Radar...',
        'urgent_events': 'eventos próximos',
        'urgent_event': 'evento próximo',
        // Drone
        'battery': 'BATERÍA',
        'mission_label': 'MISIÓN',
        'status_label': 'ESTADO',
        // Categories
        'concert': 'Conciertos',
        'festival': 'Festivales',
        'nightlife': 'Fiesta',
        'culture': 'Cultura',
        'sport': 'Deporte',
        'restaurant': 'Comida',
        'workshop': 'Talleres',
        'solar_punk': 'Eco',
        'charity': 'Solidario',
        'other': 'Otros',

        // Delivery Dashboard
        'weekly_events': 'Eventos Semanales',
        'tactical_map': 'Mapa Táctico',
        'hud_panel': 'Panel HUD',
        'tactical_mode': 'Modo Táctico',
        'active_missions': 'Misiones Activas',
        'verify_delivery': 'VERIFICAR ENTREGA',
        'otp_instruction': 'Solicita el código OTP al cliente para finalizar la misión.',
        'secure_delivery_active': 'Entrega Segura Activa',
        'otp_label': 'Código de Entrega (OTP)',
        'cancel': 'Cancelar',
        'finalize_mission': 'FINALIZAR MISION',

        // Quick Chat
        'chat_arrived': 'Ya llegué 📍',
        'chat_on_way': 'En camino 🛵',
        'chat_traffic': 'Mucha presa 🚦',
        'chat_where': '¿Dónde estás? ❓',

        // Estado Repartidor
        'status_online_title': 'ESTÁS CONECTADO',
        'status_offline_title': 'ESTÁS DESCONECTADO',
        'online_desc': 'Recibiendo pedidos en tiempo real',
        'offline_desc': 'Conéctate para empezar a ganar',
        'network_ok': 'RED OK',
        'no_network': 'SIN RED',
        'gps_ok': 'GPS OK',
        'no_gps': 'SIN GPS',
        'work_type_food': 'Comida',
        'work_type_parcel': 'Paquetes',
        'work_type_ride': 'Viajes',

        // Balance Hoy
        'today': 'Hoy',
        'deliveries': 'Entregas',
        'points': 'puntos',
        'weekly_performance': 'Rendimiento Semanal',

        // Mis Pedidos
        'active_routes': 'Pedidos en curso',
        'ready_pickup': 'LISTO PARA RECOGER',
        'en_route': 'EN CAMINO AL CLIENTE',
        'private_parcel': 'Pedido Privado',
        'tag_hot': 'CALIENTE',
        'tag_fragile': 'FRÁGIL',
        'delivery_point': 'Punto de Entrega',
        'scanning_missions': 'Buscando misiones cerca...',

        // Bolsa De Pedidos
        'order_pool': 'Bolsa de Pedidos',
        'live_tag': 'EN VIVO',
        'type_food': 'Comida',
        'type_parcel': 'Paquete',
        'earnings_label': 'Ganancia',
        'private_order': 'Pedido Privado',
        'minutes_label': 'MINUTOS',
        'km_label': 'KM',
    },
    en: {
        // General
        'search_placeholder': 'What are you craving today?',
        'hero_title': 'FLAVORS OF PARADISE',
        'near_me': 'Near Me',
        'near_you': 'Near You',
        'coming_soon': 'Coming Soon!',
        'loading': 'Loading good vibes...',
        'retry': 'Try Again',
        'connection_error': 'Oops, signal drifted away',
        'connection_error_desc': 'The sea looks rough. Check your connection and try again.',

        // Navigation
        'explore': 'Explore',
        'map': 'Map',
        'events': 'Events',
        'about': 'The Tribe',
        'sustainability': 'Eco Life',
        'blog': 'Stories',
        'profile': 'My Profile',
        'history': 'My Orders',
        'my_orders': 'My Orders',
        'logout': 'Log Out',
        'admin_panel': 'Control Panel',
        'dashboard': 'My Business',
        'courier_central': 'Delivery Central',

        // Auth
        'login': 'Log In',
        'register': 'Join Us',
        'welcome_jungle': 'Welcome to the Jungle',
        'enter_paradise': 'Enter Paradise',
        'join_tribe': 'Join the Tribe',
        'email_label': 'Your Email',
        'password_label': 'Secret Key',
        'no_account': 'Not part of it yet?',
        'has_account': 'Already have an account?',
        'auth_error': 'Hmm, those details don\'t ring a bell.',

        // Cart
        'your_order': 'Your Basket',
        'empty_cart': 'Your basket is empty',
        'empty_cart_desc': 'Fill it with Caribbean flavor!',
        'subtotal': 'Subtotal',
        'delivery_fee': 'Delivery',
        'courier_tip': 'Tip the Courier',
        'total': 'Total to Pay',
        'place_order': 'Confirm Order',
        'add_notes': 'Any extra details?',
        'notes_placeholder': 'Ex: No cilantro, sauce on the side...',

        // Categories & Filters
        'all': 'All',
        'restaurants': 'Restaurants',
        'cafes': 'Coffee Spots',
        'seafood': 'From the Sea',
        'essentials': 'Essentials',
        'eco_friendly': '100% Eco',

        // Assistant
        'ai_placeholder': 'Ask something to Sentinel...',
        'ai_title': 'COCO Caribeño - Digital Paradise Assistant',
        'quick_points': 'My Cocos?',
        'quick_eat': 'Where to eat?',
        'quick_eco': 'Sustainability',

        // Footer & Community
        'support_wa': 'WhatsApp Us',
        'order_help': 'Help with your order?',
        'rights_reserved': 'All rights reserved, mate.',
        'made_with_love': 'Made with ❤️ in the Caribbean',
        'pura_vida': 'Pura Vida!',

        // Sort
        'sort_az': 'A-Z',
        'sort_rating': 'Favorites',
        'sort_distance': 'Around the corner',
        'new': 'New',
        'local_establishment': 'Local Establishment',
        'inactive': 'Inactive',
        'closed': 'Closed',
        'busy': 'Busy',
        'operational': 'Operational',
        'active': 'ACTIVE',
        'buy_tickets': 'Buy Tickets',
        'event_store_title': 'Tickets Store',
        'event_details': 'Event Info',
        'live': 'Live',
        'coco_points': 'Coco Points',

        // Profile & Dashboard
        'abort': 'ABORT',
        'edit': 'EDIT',
        'next_objective': 'NEXT OBJECTIVE',
        'reward_incoming': 'Reward Incoming',
        'points_left': 'POINTS LEFT',
        'rewards_hub': 'REWARDS HUB',
        'request_reinforcements': 'REQ REINFORCEMENTS',
        'history_title': 'HISTORY',
        'history_desc': 'OPS LOG',
        'billing_title': 'BILLING',
        'billing_desc': 'E-INVOICING',
        'control_center': 'Control Center',
        'admin_panel_desc': 'Administration Panel',
        'ops_panel_desc': 'Operations Panel',
        'assistant_title': 'ASSISTANT',
        'assistant_desc': 'DIRECT COCO UPLINK',
        'disconnect': 'TERMINATE LINK',
        'vehicle': 'Vehicle',
        'swarm_config': 'Swarm Configuration',
        'type': 'Type',
        'plate': 'Plate',
        'status': 'Status',
        'ops_clearance': 'Ops Clearance',
        'verification': 'Verification',
        'security': 'Security',
        'lvl_1_access': 'Lvl 1 Access',
        'undefined': 'Undefined',
        'proximity': 'PROXIMITY',
        'sustainability_metric': 'SUSTAINABILITY',

        // Footer
        'footer_desc': 'The ultimate platform for the South Caribbean. Food, logistics, and community.',
        'community': 'Community',
        'legal': 'Legal',
        'privacy_policy': 'Privacy (Law 8968)',
        'terms_of_use': 'Terms of Use',
        'refunds': 'Refunds',
        'coming_soon_terms': 'Coming soon! Terms are under legal review.',
        'coming_soon_refunds': 'Coming soon! We are defining the refund policy.',

        // Merchant Dashboard
        'net_revenue': 'Net Revenue',
        'order_queue': 'Order Queue',
        'invoices_emitted': 'Invoices',
        'rating_caribe': 'Caribe Rating',
        'tactical_performance': 'Tactical Performance',
        'daily_revenue': 'Daily net revenue',
        'transparency': 'Transparency',
        'gross_sales': 'Gross Sales',
        'commission_fee': 'Commission (5%)',
        'your_balance': 'Your Balance',
        'view_payouts': 'View Payout Details',
        'customer_feedback': 'Customer Feedback',
        'reviews_count': 'Reviews',
        'no_reviews': 'No reviews yet',
        'caribe_user': 'Caribe User',
        'excellent_service': 'Excellent service',
        'order_management': 'Order Management',
        'active_orders': 'active orders',
        'sync_satellite': 'Syncing with satellite...',
        'tactical_silence': 'Tactical Silence',
        'no_active_orders': 'No active orders at the moment. Good time to check your inventory!',
        'quick_stock': 'Quick Stock',
        'search_product': 'Search product...',
        'syncing': 'Syncing...',
        'no_results': 'No results',
        'stock_changes_hint': 'Changes reflect instantly in the customer app',
        'store_status_updated': 'Store status updated',
        'error_updating_status': 'Error updating status',
        'service_mode_updated': 'Service mode updated',
        'status_updated': 'Status updated',
        'sync_command_center': 'Syncing Command Center...',
        'client': 'Client',
        'command': 'Command',
        'inventory': 'Inventory',
        'marketing': 'Marketing',
        'hacienda': 'Hacienda',
        'status_pending': 'PENDING',
        'status_preparing': 'PREPARING',
        'status_ready': 'READY',
        'status_delivered': 'DELIVERED',
        'status_cancelled': 'CANCELLED',
        'filter_all': 'ALL',
        'product_default': 'Product',
        'guest': 'Guest',
        'pickup': 'Pickup',
        'move_to': 'Move to',
        'my_business': 'My Business',
        'status_synced': 'Synced',
        'status_offline': 'Offline',
        'status_on_way': 'On Way',
        'busy_mode': 'Busy Mode',
        'status_active': 'Active',
        'status_normal': 'Normal',
        'store_status_label': 'Store Status',
        'status_online': 'Online',
        'settings': 'Settings',
        'new_order': 'NEW ORDER!',
        'customer': 'Customer',
        'enter_command': 'ENTER COMMAND',
        'order_total': 'Order Total',
        // Audit 2: Utilities
        'bus_schedules': 'Schedules',
        'bus_company': 'MEPE & Caribe Sur',
        'bus_direct': 'Direct',
        'city_sjo': 'SJO',
        'city_pv': 'PV',
        'city_limon': 'Limón',
        'bus_duration': '~4.5h',
        'freq_hourly': 'Hourly',
        'bus_warning': 'Arrive 30 mins early. Buy tickets at counter.',
        'push_title': 'Enable Notifications?',
        'push_desc': 'Get instant alerts about your order status and exclusive offers.',
        'push_later': 'Not Now',
        'push_enable': 'Enable',
        'push_success_title': '🎉 Notifications Enabled',
        'push_success_desc': 'You will receive order alerts and special offers',
        // Audit 3: Global Notifications
        'status_update_toast': 'Status updated in real-time',
        'new_order_received': 'New Order Received!',
        'new_mission': '🚀 New Mission Available',
        'mission_desc': 'Nearby merchant needs pickup',
        'driver_arriving': '🚀 Driver is arriving!',
        'inventory_updated': 'Inventory Updated',
        'inventory_desc': 'Product availability has changed.',
        'session_expired': 'Session Expired',
        'session_expired_desc': 'Real-time session expired. Re-authenticating...',
        // Audit 4: Map Experience
        'search_map_placeholder': 'Find events or places...',
        'dynamic_weather': 'Dynamic Weather',
        'tactical_scanlines': 'Tactical Scanlines',
        'show_merchants': 'Show Places',
        'show_events': 'Show Events',
        'strategic_patrol_mode': 'Strategic Patrol Mode',
        'ambient_cycle': 'Ambient Cycle',
        'my_location': 'My Location',
        'categories': 'Categories',
        'visualization': 'Visualization',
        'scan_lines': 'Scan Lines',
        'places': 'Places',
        'gps': 'GPS',
        'patrol': 'Patrol',
        'ambience': 'Ambience',
        'active_mission': 'Active Mission',
        'private_mission': 'Private Mission',
        'release_camera': 'Release Camera',
        'fix_camera': 'Fix Camera',
        'destination': 'Destination',
        'open_chat': 'Open Chat',
        'waze_nav': 'Navigate Waze',
        'pickup_order': 'PICKUP ORDER',
        'complete_delivery': 'COMPLETE DELIVERY',
        'featured_event': 'Featured Event',
        'attendees': 'Attendees',
        'buy_ticket_btn': 'BUY TICKET',
        'vip_event': 'VIP Event',
        // Map Indicators
        'time_sunrise': 'Caribbean Sunrise',
        'time_day': 'Full Sun',
        'time_golden': 'Golden Hour',
        'time_night': 'Tropical Night',
        'time_stealth': 'Stealth Mode',
        'exploration_mode': 'Exploration Mode Active',
        'sync_radar': 'Syncing Radar...',
        'urgent_events': 'upcoming events',
        'urgent_event': 'upcoming event',
        // Drone
        'battery': 'BATTERY',
        'mission_label': 'MISSION',
        'status_label': 'STATUS',
        // Categories
        'concert': 'Concerts',
        'festival': 'Festivals',
        'nightlife': 'Party',
        'culture': 'Culture',
        'sport': 'Sports',
        'restaurant': 'Food',
        'workshop': 'Workshops',
        'solar_punk': 'Eco',
        'charity': 'Charity',
        'other': 'Other',

        // Delivery Dashboard
        'weekly_events': 'Weekly Events',
        'tactical_map': 'Tactical Map',
        'hud_panel': 'HUD Panel',
        'tactical_mode': 'Tactical Mode',
        'active_missions': 'Active Missions',
        'verify_delivery': 'VERIFY DELIVERY',
        'otp_instruction': 'Ask customer for OTP code to finish mission.',
        'secure_delivery_active': 'Secure Delivery Active',
        'otp_label': 'Delivery Code (OTP)',
        'cancel': 'Cancel',
        'finalize_mission': 'FINISH MISSION',

        // Quick Chat
        'chat_arrived': 'I arrived 📍',
        'chat_on_way': 'On my way 🛵',
        'chat_traffic': 'Heavy traffic 🚦',
        'chat_where': 'Where are you? ❓',

        // Estado Repartidor
        'status_online_title': 'YOU ARE ONLINE',
        'status_offline_title': 'YOU ARE OFFLINE',
        'online_desc': 'Receiving orders in real-time',
        'offline_desc': 'Go online to start earning',
        'network_ok': 'NET OK',
        'no_network': 'NO NET',
        'gps_ok': 'GPS OK',
        'no_gps': 'NO GPS',
        'work_type_food': 'Food',
        'work_type_parcel': 'Parcel',
        'work_type_ride': 'Rides',

        // Balance Hoy
        'today': 'Today',
        'deliveries': 'Deliveries',
        'points': 'points',
        'weekly_performance': 'Weekly Performance',

        // Mis Pedidos
        'active_routes': 'Active Routes',
        'ready_pickup': 'READY TO PICKUP',
        'en_route': 'EN ROUTE',
        'private_parcel': 'Private Parcel',
        'tag_hot': 'HOT',
        'tag_fragile': 'FRAGILE',
        'delivery_point': 'Delivery Point',
        'scanning_missions': 'Scanning for missions nearby...',

        // Bolsa De Pedidos
        'order_pool': 'Order Pool',
        'live_tag': 'LIVE',
        'type_food': 'Food',
        'type_parcel': 'Parcel',
        'earnings_label': 'Take',
        'private_order': 'Private Order',
        'minutes_label': 'MINS',
        'km_label': 'KM',
    }
};

export const useLanguageStore = create<LanguageState>()(
    persist(
        (set, get) => ({
            language: 'es',
            setLanguage: (language) => set({ language }),
            t: (key) => {
                const lang = get().language;
                return translations[lang][key as keyof typeof translations['es']] || key;
            }
        }),
        {
            name: 'paradise-language-storage',
        }
    )
);
